# Generated by Django 5.0.14 on 2026-09-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payer_phone',
            field=models.CharField(blank=True, help_text='Phone the student paid from (manual payments)', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='momo_code',
            field=models.CharField(blank=True, help_text='Mobile-money transaction ID (or Pesapal confirmation code)', max_length=100),
        ),
    ]
