# Generated by Django 5.0.14 on 2026-09-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Qiora for Law Students', max_length=100)),
                ('tagline', models.CharField(blank=True, default='Learn the law skills lecture halls skip.', max_length=200)),
                ('momo_number', models.CharField(blank=True, max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('support_phone', models.CharField(blank=True, max_length=20)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
