# Generated by Django 5.0.14 on 2026-09-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='platform_fee_percent',
            field=models.PositiveIntegerField(default=10, help_text='Share of each payment the platform keeps; the rest is owed to the teacher.'),
        ),
    ]
