# Generated by Django 5.0.14 on 2026-09-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_platform_fee_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Qiora for Students', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tagline',
            field=models.CharField(blank=True, default='Learn practical skills for any course.', max_length=200),
        ),
    ]
