# Generated by Django 5.0.14 on 2026-09-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='headline',
            field=models.CharField(blank=True, help_text='Shown on the homepage instructor spotlight, e.g. "Contracts that hold up"', max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, help_text='e.g. "Kampala"', max_length=80),
        ),
    ]
