# Generated by Django 5.0.14 on 2026-09-19 15:12

from django.db import migrations, models


def verify_existing_teachers(apps, schema_editor):
    # Teachers that already exist were added by an admin, so they are trusted.
    User = apps.get_model('accounts', 'User')
    User.objects.filter(role='teacher').update(is_verified_teacher=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_headline_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Short introduction shown on the instructor block'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified_teacher',
            field=models.BooleanField(default=False, help_text='Verified teachers can publish courses. Unverified teachers save drafts only.'),
        ),
        migrations.AddField(
            model_name='user',
            name='payout_phone',
            field=models.CharField(blank=True, help_text='Mobile-money number teachers are paid to', max_length=20),
        ),
        migrations.RunPython(verify_existing_teachers, migrations.RunPython.noop),
    ]
