# Generated by Django 5.0.14 on 2026-09-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, choices=[('legal_writing', 'Legal Writing & Drafting'), ('moot_court', 'Moot Court & Advocacy'), ('case_law', 'Case Law & Precedent'), ('constitutional', 'Constitutional Law'), ('contract', 'Contract & Commercial Law'), ('criminal', 'Criminal Law & Procedure'), ('research', 'Legal Research Methods'), ('bar_prep', 'Bar Course Prep'), ('human_rights', 'Human Rights Law'), ('adr', 'Alternative Dispute Resolution'), ('internship', 'Internship & Clerkship Skills'), ('international', 'International & Comparative Law'), ('family_land', 'Family & Land Law')], max_length=20),
        ),
    ]
