# Generated by Django 5.0.14 on 2026-09-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=15),
        ),
        migrations.AddField(
            model_name='course',
            name='subtitle',
            field=models.CharField(blank=True, help_text='One line under the title, e.g. "Draft your first plaint in an afternoon"', max_length=200),
        ),
        migrations.AddField(
            model_name='lesson',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Length in minutes'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='kind',
            field=models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('pdf', 'PDF / notes')], default='video', max_length=10),
        ),
        migrations.AddField(
            model_name='lesson',
            name='module_title',
            field=models.CharField(blank=True, help_text='Group lessons, e.g. "Module 01: Setup"', max_length=120),
        ),
    ]
