# Generated by Django 5.0.14 on 2026-09-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_level_course_subtitle_lesson_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, choices=[('business', 'Business & Entrepreneurship'), ('finance', 'Accounting & Finance'), ('technology', 'Technology & Programming'), ('data', 'Data & Analytics'), ('science', 'Science & Mathematics'), ('health', 'Health & Medicine'), ('engineering', 'Engineering'), ('education', 'Education & Teaching'), ('arts_design', 'Arts & Design'), ('languages', 'Languages & Communication'), ('agriculture', 'Agriculture'), ('career', 'Career & Personal Growth'), ('legal_writing', 'Legal Writing & Drafting'), ('moot_court', 'Moot Court & Advocacy'), ('case_law', 'Case Law & Precedent'), ('constitutional', 'Constitutional Law'), ('contract', 'Contract & Commercial Law'), ('criminal', 'Criminal Law & Procedure'), ('research', 'Legal Research Methods'), ('bar_prep', 'Bar Course Prep'), ('human_rights', 'Human Rights Law'), ('adr', 'Alternative Dispute Resolution'), ('internship', 'Internship & Clerkship Skills'), ('international', 'International & Comparative Law'), ('family_land', 'Family & Land Law')], max_length=20),
        ),
    ]
